sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t green .
  # create docker image from Dockerfile
  
  #- docker run -d -p 127.0.0.1:80:4567 20289472/green /bin/sh -c "cd /root/green; bundle exec foreman start;"
  #- docker ps -a
  #- docker run 20289472/green /bin/sh -c "cd /root/green; bundle exec rake test"

script:
 - docker run green /bin/sh -c "ant; ant test"; 
 # search for docker image to run ant and ant test in. 
 


